export const DOMAIN = 'https://react-memory-mern.herokuapp.com'

export const LIMIT = 10

export const HTTP_HEADER_JSON = { 'Content-Type': 'application/json' }

export const HTTP_READ = 'GET'
export const HTTP_POST = 'POST'
export const HTTP_PUT = 'PUT'
export const HTTP_DELETE = 'DELETE'

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAILURE = 'GET_POST_FAILURE'

export const GET_DELETED_POST_REQUEST = 'GET_DELETED_POST_REQUEST'
export const GET_DELETED_POST_SUCCESS = 'GET_DELETED_POST_SUCCESS'
export const GET_DELETED_POST_FAILURE = 'GET_DELETED_POST_FAILURE'

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const RESTORE_POST_REQUEST = 'RESTORE_POST_REQUEST'
export const RESTORE_POST_SUCCESS = 'RESTORE_POST_SUCCESS'
export const RESTORE_POST_FAILURE = 'RESTORE_POST_FAILURE'

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE'
